.eslintrc.json, .github/dependabot.yml, .github/workflows/codeql.yml, .github/workflows/commitlint.yml, .github/workflows/dependency-review.yml, .github/workflows/node.js.yml, .github/workflows/release.yml, commitlint.config.js, package-lock.json, package.json, src/fluent/types.ts, src/types.ts
Export `KubernetesObject` and `KubernetesListObject` as often-needed imports for [Pepr](https://pepr.dev/). 
New CI checks:
- dependabot
- codeql
- unit tests (node 18 + latest)
- commitlint PR title validation
=> feat: add additional ci stages

src/fetch.ts
just because we're not ok, doesn't mean the data payload is helpful in Kubernetes case, this contains the exact why of a potential error.
will need some additional testing, and use cases. like if we're getting a failed connection, or there's no body to the non-200 response.
in theory we can also try to populate the message, but the statusText is an HTTP text error, and the body payload is something else.
=> fix(fetch): always set data field, even on `status.ok == false`

src/fluent/utils.test.ts
fix: filters for field and label selectors weren't tested. also added a test for a Kind without a version.
=> fix: tests for coverage

src/fluent/apply.ts, src/fluent/index.test.ts, src/fluent/index.ts, src/fluent/types.ts, src/fluent/utils.test.ts, src/fluent/utils.ts
@lucasrod16  discovered a bug in Pepr when trying to `apply` a secret that was initially created by Zarf:
```typescript
try {
await K8s(kind.Secret).Apply({
metadata: {
name: secretName,
namespace: ns,
},
data: {
data: secret.data.data,
},
});
} catch (err) {
Log.error(
`Error: Failed to update package secret '${secretName}' in namespace '${ns}'`,
);
}
```
The error had to do with a `FieldManagerConflict`:
```
"Apply failed with 1 conflict: conflict with \\\"zarf\\\" using v1: .data.data\",\"reason\":\"Conflict\",\"details\":{\"causes\":[{\"reason\":\"FieldManagerConflict\",\"message\":\"conflict with \\\"zarf\\\" using v1\",\"field\":\".data.data\"}]},\"code\":409},\"ok\":false,\"status\":409,\"statusText\":\"Conflict\"}"}
```
There should be more options exposed in the future but this …
=> feat: force options on apply

package-lock.json, package.json
Temporary until https://github.com/flexdinesh/browser-or-node/pull/25 is merged/released.
=> fix: override browser-or-node until upstream is fixed for Node21

package-lock.json, package.json
Apparently package.json overrides are not respected by npx, so having to fork quicktype until that is resolved.
=> fix: fork quicktype-core temporarily due to Node21 dep bug

src/kinds.test.ts, src/kinds.ts, src/upstream.ts
from chatgpt, looks correct, we want to make sure we have the detail to make decisions to recreate a docker pull secret based on them changing remotely (ECR). The code currently gives you the correct object, but typed to the old object type causing mismatching.
---
`CoreV1Event` and `EventV1Event` in Kubernetes refer to different versions and structures of events. Below is a comparison of the two:
- Part of the `core/v1` API group.
- The original event resource type, present since early Kubernetes versions.
- Commonly used and interacted with via `kubectl get events`.
- Events are used primarily for debugging and do not guarantee comprehensive information about the cluster state.
- Introduced in later Kubernetes versions, starting as `events.k8s.io/v1beta1` in Kubernetes 1.10 and …
=> fix: event types mixed up and add both types of events

src/fluent/index.test.ts, src/fluent/index.ts, src/fluent/types.ts, src/index.ts
This exposes a `.Raw()` call that mirrors `kubectl get --raw` for performing advanced calls when the fluent API alone isn't enough. Also properly exports the `waitForCluster()` helper function and all generic K8s models under `models` for advanced usage.
=> feat: add `K8s().Raw()` function for arbitrary wrapped API calls

src/generate.ts
Updated filepath in generate.ts readOrFetchCrd function to check to see if the source path is absolute or relative and handle them correctly:
```ts
if (source[0] === "/") { // If the source is an absolute path
filePath = source;
} else { // If the source is a relative path
filePath = path.join(process.cwd(), source);
}
```
=> chore: updated filepath to correctly handle absolute and relative paths

src/generate.test.ts, src/generate.ts
This adds `plural` to the CRD generation so that it can properly be used when generating URL paths to interact with K8s objects in a cluster.
=> feat: add `plural` to CRD generation

package-lock.json, package.json
https://github.com/defenseunicorns/kubernetes-fluent-client/actions/workflows/release.yml
An update QuickType Core broke our KFC Release pipeline
```bash
[Release: node_modules/quicktype-core/dist/input/JSONSchemaInput.d.ts#L1](https://github.com/defenseunicorns/kubernetes-fluent-client/commit/793ca7b03bc81756541cc513871728a24f1d4a9b#annotation_21521061930)
Could not find a declaration file for module 'urijs'. '/home/runner/work/kubernetes-fluent-client/kubernetes-fluent-client/node_modules/urijs/src/URI.js' implicitly has an 'any' type.
```
=> build: revert quick-type core bc it breaks

.github/workflows/commitlint.yml
This should mitigate [this](https://github.com/defenseunicorns/kubernetes-fluent-client/security/code-scanning/3) vulnerability
=> chore: add permissions to commitlint workflow

package-lock.json, package.json
The typefest update is missing a depedency that blocks release
=> chore: revert bc release failed

.github/workflows/node.js.yml, .github/workflows/release.yml, e2e/cli.e2e.test.ts
Run `npm run test:e2e` in CI.
Fixes #392
=> chore(testing): add E2E tests to CI

src/fluent/http2-watch.spec.ts, src/fluent/watch.ts
Adds unit test, attempts to optimize memory consumption
Fixes #
Relates to #
=> feat: http2 optimized

src/fluent/http2-watch.spec.ts, src/fluent/watch.ts
Adds an http2 watcher that is configured through WatchConfig. We needed to change the title to try and kick off a release.
Fixes #
Relates to #
=> feat(watcher): http2 in the watcher

src/fluent/types.ts, src/fluent/watch.ts
Reduces the memory footprint of http2Watch and includes refactoring
Soak Test: https://github.com/defenseunicorns/pepr/actions/runs/11355812600/job/31585909300
Fixes #424 
Relates to #
=> fix: reduce memory footprint and refactor

src/upstream.ts
PolicyRule does not need to be an upstream type
Fixes #439 
Relates to #
=> chore: remove policyrule from upstream types

src/fluent/watch.ts
errorHandler - should only scheduleReconnect if using http2
Fixes #440 
Relates to #
=> fix: errorHandler - should only schedulereconnect if using http2

eslint.config.mjs, package-lock.json, package.json
```
> eslint src && prettier . --check
Oops! Something went wrong! :(
ESLint: [9](https://github.com/defenseunicorns/kubernetes-fluent-client/actions/runs/11673947912/job/32505660897?pr=399#step:5:10).14.0
ESLint couldn't find an eslint.config.(js|mjs|cjs) file.
From ESLint v9.0.0, the default configuration file is now eslint.config.js.
If you are using a .eslintrc.* file, please follow the migration guide
to update your configuration file to the new format:
https://eslint.org/docs/latest/use/configure/migration-guide
If you still have problems after following the migration guide, please stop by
https://eslint.org/chat/help to chat with the team.
npx @eslint/migrate-config .eslintrc.json
Migrating .eslintrc.json
Wrote new config to ./eslint.config.mjs
You will need to install the …
```
=> chore: eslint migration

CODEOWNERS
Make `CODEOWNERS` reference `@defenseunicorns/pepr` instead of individuals. Adds @daveworth to file
Fixes #480 
Relates to #
=> chore: codeowners to reference group

package-lock.json, package.json
Force the transitive test dep to use the non-vuln version of `cross-spawn`.
Cuz I saw this when I tried to build today:
```bash
workstation-ubuntu2404:~/workspace/kubernetes-fluent-client$ npm audit
cross-spawn  7.0.0 - 7.0.4
Severity: high
Regular Expression Denial of Service (ReDoS) in cross-spawn - https://github.com/advisories/GHSA-3xgq-45jj-v275
fix available via `npm audit fix`
node_modules/npm/node_modules/cross-spawn
1 high severity vulnerability
To address all issues, run:
npm audit fix
```
```bash
workstation-ubuntu2404:~/workspace/kubernetes-fluent-client$ npm ls cross-spawn
kubernetes-fluent-client@0.0.0-development /home/user/workspace/kubernetes-fluent-client
├─┬ @kubernetes/client-node@1.0.0-rc7
│ └─┬ tar@7.2.0
│   └─┬ minizlib@3.0.1
│     └─┬ rimraf@5.0.7
│       └─┬ …
```
=> fix: override transitive test dep f/ high vuln (cross-spawn)

.github/dependabot.yml
@kubernetes/client-node created a release that breaks our ability to generate classes from CRDs. It also breaks CI. The release has no release notes either. Very strange. We definitely should skip this. 
Fixes #
Relates to #
=> chore: ignore breaking release of @kubernetes/client-node

package-lock.json, package.json
PR #599 has our dependabot updates along with the kubernetes/client-node update which would break KFC. Since we cannot close a dependabot PR (or it we would lose future updates to those deps) we can unblock prod updates manually by updating the dependencies other than the kubernetes/client-node.
Fixes #
Relates to #591
=> chore: bump prod deps - not kubernetes/client-node

package-lock.json, package.json
When `@kubernetes/client-node` was released 21 days ago, it created breaking changes in KFC. Due to this, we cannot get our prod dependency updates from dependabot
Fixes #
Relates to #
=> fix: bump undici and typefest

src/kinds.test.ts, src/kinds.ts, src/upstream.ts
The generated `Endpoint` from the upstream library where our types are consumed is incorrect. It has only a subset of fields making it difficult to assert on the shape of the object in Pepr. This PR adds the `apiVersion`, `metadata`, `kind`, and corrects the `subnet` field to be an array like in the real endpoint schema.
```plaintext
KIND:       Endpoints
VERSION:    v1
DESCRIPTION:
Endpoints is a collection of endpoints that implement the actual service.
Example:
Name: "mysvc",
Subsets: [
{
Addresses: [{"ip": "10.10.1.1"}, {"ip": "10.10.2.2"}],
Ports: [{"name": "a", "port": 8675}, {"name": "b", "port": 309}]
},
{
Addresses: [{"ip": "10.10.3.3"}],
Ports: [{"name": "a", "port": 93}, {"name": "b", "port": 76}]
},
]
FIELDS:
apiVersion	<string>
APIVersion defines the versioned schema of this …
```
=> fix: override generated endpoint class to correct type

src/kinds.test.ts, src/kinds.ts, src/upstream.ts
We were exporting `Endpoint` instead of `Endpoints`, which is the correct for endpoints in kubernetes.
```yaml
> k explain ep | head -2
KIND:       Endpoints
VERSION:    v1
> k api-resources | egrep "endpoints"
endpoints                           ep           v1                                true         Endpoints
```
The endpoint type was incorrect and was missing fields
Fixes #622
Fixes #620 
Relates to #620
=> fix: fix ep

CONTRIBUTING.md
Avoid redundancy and add clarity to `CONTRIBUTING.md` so that users know when it is okay to not create an issue and rephrase the second line around commits being signed since it is in there twice.
The reason for this PR is to release since Undici bumped. 
Fixes #
Relates to #
=> fix: avoid redundancy and add clarity to contributing

e2e/main.e2e.test.ts, e2e/watch.e2e.test.ts, tsconfig.json
In support of https://github.com/defenseunicorns/kubernetes-fluent-client/issues/591, this is a e2e test for watch
Fixes #680 
Relates to #
=> chore: e2e test for watch

e2e/main.e2e.test.ts, e2e/tsconfig.json, e2e/watch.e2e.test.ts, eslint.config.mjs, package.json
#691 lints E2Es, but the configuration causes some issues when `npm run format:check` or during lint with the commit hooks. We'll see an error along the lines of:
```text
0:0  error  Parsing error: "parserOptions.project" has been provided for @typescript-eslint/parser.
The file was not found in any of the provided project(s): e2e/webapp-v1alpha1.ts
```
Because we store `e2e` outside of `src`, our `tsconfig.json` file considers `e2e` tests as outside of scope. What we can do is add a tsconfig for the `e2e` tests and update the eslint config accordingly.
Relates to #691
=> fix: handle eslint exclusions on `e2e/`  when `format:check` runs

e2e/watch.e2e.test.ts, src/fluent/watch.test.ts, src/fluent/watch.ts
This PR removes an unused function and ensures that the code in `utils.ts` is tested by our E2E suite. Here's how coverage was ensured:
```
describe("getToken", () => {
// Called by getHeaders, used by Watcher.#watch, covered by `watch.e2e.test.ts`
});
describe("getHTTPSAgent", () => {
// Called by k8sCfg, used in `watch.e2e.test.ts`, `main.e2e.test.ts`
});
describe("getHeaders", () => {
// Called by K8s Config, covered by `watch.e2e.test.ts`, `main.e2e.test.ts` 
// Called by watch.ts:#watch, covered by `watch.e2e.test.ts`, `main.e2e.test.ts`
});
describe("pathBuilder Function", () => {
// Called by watch.ts:getCacheId,#buildURL, covered by `watch.e2e.test.ts`
// NOTE: getCacheId is unused in production code. Remove it.
// Called by k8sExec, covered by `watch.e2e.test.ts`, and …
```
=> chore: ensure e2e coverage for utils.ts

src/cli.ts
Related to #752 to handle CLI output
hotfix for #752
=> fix: display just the version when --version is passed

src/index.ts, src/patch.ts
We were patching from of the ingress rule for the network policy definition. Since switching to the latest `@kubernetes/client-node` it is fixed
**DEBUGGING**
First deploy UDS Core to get a current ingress network policy
```bash
k get netpol allow-keycloak-ingress-8080-keycloak-istio-admin-gateway -n keycloak -oyaml
```
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
annotations:
uds/description: 8080-keycloak Istio admin gateway
creationTimestamp: "2025-07-15T14:17:18Z"
generation: 1
labels:
uds/generation: "1"
uds/package: keycloak
name: allow-keycloak-ingress-8080-keycloak-istio-admin-gateway
namespace: keycloak
ownerReferences:
- apiVersion: uds.dev/v1alpha1
kind: Package
name: keycloak
uid: 419388e1-9f4d-4411-9708-d41f5066c835
resourceVersion: "1723"
uid: …
```
=> fix: remove unneeded patch

src/index.ts, src/patch.ts
Reverts defenseunicorns/kubernetes-fluent-client#814
```json
{"level":50,"time":1753122086570,"pid":17,"hostname":"pepr-uds-core-watcher-7b7bbc5575-g5dqp","component":"operator.reconcilers","err":{"type":"Error","message":"failed to create typed patch object (keycloak/allow-keycloak-ingress-ambient-healthprobes; networking.k8s.io/v1, Kind=NetworkPolicy): .spec.ingress[0]._from: field not declared in schema","stack":"Error: failed to create typed patch object (keycloak/allow-keycloak-ingress-ambient-healthprobes; networking.k8s.io/v1, Kind=NetworkPolicy): .spec.ingress[0]._from: field not declared in schema\n    at networkPolicies (/app/module-276430c9fafa99cfeff5114db339e02e24948c43c21d97c32b80c54354aab4a4.js:1:76470)\n    at process.processTicksAndRejections …
```
=> fix: revert patch due to errors in uds core

e2e/main.e2e.test.ts, src/fluent/index.test.ts, src/fluent/index.ts, src/fluent/types.ts, src/generate.test.ts
This PR adds the ability to add or remove finalizers from Kubernetes resources. Due to limitations in Kubernetes around JSON Patch and requiring a patch file Server Side Apply was the best option to ensure we are able to both and remove without needing a patch file. 
Due to the nature of Server Side Apply we first fetch the resource and then Apply the new state of the resource with the updated finalizers
Fixes #807 
Relates to #
=> feat: finalize in kfc

CONTRIBUTING.md
ts-node command does not work to run the cli, we need to use tsx
```bash
> npx ts-node src/cli.ts      
Error: Cannot find module '/Users/cmwylie19/kubernetes-fluent-client/src/generate.js' imported from /Users/cmwylie19/kubernetes-fluent-client/src/cli.ts
at finalizeResolution (node:internal/modules/esm/resolve:274:11)
at moduleResolve (node:internal/modules/esm/resolve:859:10)
at defaultResolve (node:internal/modules/esm/resolve:983:11)
at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:799:12)
at ModuleLoader.#cachedDefaultResolve (node:internal/modules/esm/loader:723:25)
at ModuleLoader.resolve (node:internal/modules/esm/loader:706:38)
at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:307:38)
at ModuleJob.#link …
```
=> chore: ts-node command does not work - use tsx

package-lock.json, package.json
[VAT](https://vat.dso.mil/vat/image?imageName=opensource/defenseunicorns/pepr/controller&tag=v0.55.0-arm64&branch=master) has flagged the version of tar-fs being used by `@kubernetes/client-node` as highly vulnerable.
```bash
tar-fs-3.0.10
/app/node_modules/tar-fs
tar-fs provides filesystem bindings for tar-stream. Versions prior to 3.1.1, 2.1.3, and 1.16.5 are vulnerable to symlink validation bypass if the destination directory is predictable with a specific tarball. This issue has been patched in version 3.1.1, 2.1.4, and 1.16.6. A workaround involves using the ignore option on non files/directories.
```
We need to override the version of `tar-fs` to greater than `3.1.1` where it is fixed
**Before**
```bash
> npm ls tar-fs 
kubernetes-fluent-client@0.0.0-development …
```
=> fix: override tar-fs vulnerable version
