defenseunicorns/kubernetes-fluent-client

- src/fluent/index.ts
- src/fluent/types.ts
> fix: require label & field selector values

- CODEOWNERS
Adding the Pepr team to CODEOWNERS
> chore: add to codeowners

- package-lock.json
- package.json
- src/cli.ts
Updated yargs in cli.ts to return the version number listed in the package.json file.
> feat: updated yargs to return version number

- package-lock.json
- package.json
- src/cli.ts
Removed the git semantic-release plugin.
> feat: add version to kfc cli

- .github/workflows/scorecard.yml
- included openssf scorecard github action
> chore: included openssf scorecard

- src/upstream.ts
> feat: add endpoint

- .github/workflows/commitlint.yml
Same fix as the following:
- https://github.com/defenseunicorns/pepr/pull/578
- https://github.com/defenseunicorns/zarf/pull/2418
- https://github.com/defenseunicorns/pkg/pull/60
> fix: commitlint workflow

- src/fluent/watch.ts
Make allowWatchBookmarks configurable
> fix: allowWatchBookmarks should be configurable

- README.md
- src/fluent/index.ts
- src/fluent/types.ts
- src/fluent/utils.ts
- src/helpers.test.ts
- src/helpers.ts
Fixes #214 
A need was brought up for the KFC to have a logging mechanism. This will make e2e and journey testing clusters for UDS and Software Factory easier.
> feat: log support in KFC

- README.md
Need to release to mitigate the `@kubernetes/client-node`. This makes a small change showing how to install the KFC from README.md
> fix: update README.md and release to get around ws vulnerability complaints

- README.md
This PR is meant to trigger a release of dependency updates and add a section to `README.md` indicating where to go for questions
> build: trigger patch release and add community section to README.md

- .github/workflows/node.js.yml
- .github/workflows/release.yml
Add code to create the dist
Fixes #419 
Relates to #
> fix(dist): add dist folder before release

- src/fluent/watch.ts
reconnects client after checkResync
Fixes #
Relates to #
> fix: checkresync function

- src/upstream.ts
Exposes PolicyRule in upstream.ts for use in Pepr.
...
Fixes #432 
Relates to #
> feat: adding PolicyRule to upstream

- package-lock.json
- package.json
- src/fluent/watch.ts
Removes byline and legacy fetch from KFC.
Fixes #457 
Relates to #
> fix: remove legacy fetch

- .github/workflows/e2e.yml
- package.json
During development the crd generation was pointing to a feature branch. Said branch has since been deleted. 
Fixes #
Relates to #
> chore: update crd generation to point to main branch

- .npmignore
- package.json
Leaves only the essential files in newly pub'd packages.
Fixes #499
> fix: remove cruft from pub'd package

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
Creates a contributor guide for KFC explaining how to test, run the project, and contribute. Since the CODE_OF_CONDUCT is a prereq for contributing, I added it into this PR but it can be split into a different PR if we deem necessary. 
Fixes #479 
Relates to #
> chore: contributor guide for kfc

- src/fluent/types.ts
This type is required for Pepr [1770](https://github.com/defenseunicorns/pepr/pull/1770) to reduce complexity
Fixes #
Relates to #[1770](https://github.com/defenseunicorns/pepr/pull/1770)
> feat: expose watcher class types

- src/upstream.ts
exports genericKind
Fixes #
Relates to #
> fix: export generic-kind

- src/fluent/index.ts
- src/fluent/utils.ts
- src/upstream.ts
This PR refactors some of the logic around generation of an Eviction API call.
None
> fix: refactor eviction URL generation

- e2e/kinds.e2e.test.ts
e2e test for kinds.
Fixes #678 
Relates to #
> chore: kinds e2e test

- .github/workflows/dependency-review.yml
- .lintstagedrc.json
This PR adds a CI check for circular dependencies.
Fixes #699
> chore: check for circular dependencies in CI

- .prettierignore
- e2e/kinds.e2e.test.ts
- e2e/main.e2e.test.ts
- e2e/watch.e2e.test.ts
Removes the e2e from prettier ignore and formats them 
Fixes #
Relates to #
> chore: prettier e2e

- src/fluent/watch.test.ts
Remove the skipped tests from `watch.test.ts` by mocking kubeConfig
Fixes #779
Relates to #
> chore: mock kubeconfig in `watch.test.ts` in order to remove skipped test
